### ISSUE TITLE
Feature Set Todo Summary

### ISSUE THREAD

**Issue by he00741098** [he00741098/pogoot#96]
- [ ] Search bar
- [ ] Dashboard
- [ ] Recommendation system
- [ ] Email sending system
- [ ] Better Notecard creation system
- [ ] Image storage
- [ ] Account recovery - Forgot password
- [ ] Better TOS/other policies
- [ ] Improve UI
- [ ] Fix bugs
- [ ] Mobile/smaller screen support
- [ ] Improve LOGO
- [ ] Kahoot system
- [ ] More testing?
- [ ] More notecard types
- [ ] Historical Events timeline tool
- [ ] Graph support
